wandb_version: 1

eta:
  desc: null
  value: 0.1
max_depth:
  desc: null
  value: 6
nthread:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    code_path: code/modelling.py
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706704502.381711
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      - 105
      2:
      - 5
      - 6
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    session_history: code\_session_history.ipynb
