name: ci demo
run-name: ci demo
on: [push]
jobs:
    sample-job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: hello
          run: |
            echo "hello world"
        - name: run python script
          run: |
            pip install -r requirements.txt
            python client/ci.py
