name: Compare runs on comment
run-name: Compare runs on comment
on:
  issue_comment:
    types:
      - created
  
  discussion_comment:
    types:
      - created

permissions:
    actions: write
    contents: write
    id-token: write
    issues: write
    pull-requests: write
    
jobs:
  Listen-for-comments:
    if: contains(github.event.comment.body, '/wandb')
    runs-on: ubuntu-latest
    steps:        

    - name: Get repo contents
      uses: actions/checkout@v3

    - name: install dependencies
      run: pip install ghapi wandb

    - name: parse value from commands
      id: get-runid-value # attaches a reference id which can be later used to refer this step
      shell: python
      run: |
        import re, os
        comment = os.getenv('PR_COMMENT', '') 
        # if the PR_COMMENT env variable is found return it else return ""
        match = re.search('/wandb[\s+](\S+)', comment)

        # Here we create a new env variabe depending upon whether the right comment is found
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f: 
          if match:
            print(f'VAL_FOUND=true', file=f)
            print(f'RUN_ID={match.group(1)}', file=f)
            # Passes the link to the RUN_ID
          else:
            print(f'VAL_FOUND=false', file=f)
      env:
        PR_COMMENT: ${{ github.event.comment.body }} # set the PR_COMMENT env variable

    - name: Generate the comparison report
      if: steps.get-runid-value.outputs.VAL_FOUND == 'true'
      id: wandb-report
      run: python compare_runs.py
      env:
        WANDB_ENTITY: harsh-ajay-jadhav
        WANDB_PROJECT: Higgs-Boson
        BASELINE_TAG: baseline
        RUN_ID: "${{ steps.get-runid-value.outputs.RUN_ID }}"
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    - name: Make a comment with the GitHub API
      uses: actions/github-script@v6
      if: steps.wandb-report.outcome == 'success' # accessing the outputs from a step
      with:
        script: |
           var msg = `A comparison between the linked run and baseline is available [in this report](${process.env.REPORT_URL})`
           github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            });
      env:
        REPORT_URL: "${{ steps.wandb-report.outputs.REPORT_URL }}"
        
