name: Simple train 
run-name: Simple train
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v1
      - name: Train model & Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          cat results.txt >> report.md
          cml comment create report.md
        
          # Post reports as comments in GitHub PRs
          # cat results.txt >> report.md
          # cml comment create report.md
