name: Simple train 
run-name: Simple train
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v4
      - name: Train model & Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          echo "## Model Metrics:" > results.md
          cat results.txt >> results.md
        
          
          
          # Post reports as comments in GitHub PRs
          # cat results.txt >> report.md
          # cml comment create report.md
